### PR TITLE
Rdm 5327 redo record page based on figma

### PR DESCRIPTION
**Pull request by adammckenzie**
This pull request includes the changes to the metadata fields, side panel to access dataset, citation generator, and additional metadata at the bottom of the page. Data used for more fields and different languages was:

{
        "dc_type_s":"Dataset",
        "dc_rights_s":"Public",
        "dc_rights_uri_s":"CC0 1.0 Universal (CC0 1.0) Public Domain Dedication  https://creativecommons.org/publicdomain/zero/1.0/",
        "dc_subject_en_sm":["agriculture"],
        "dc_subject_fr_sm":["agriculture"],
        "layer_slug_s":"geodisy:open_f48efc96-a51f-40f9-aaa0-90797f92e269",
        "dc_title_en_s":"1 km agricultural mask from the Crop Condition Assessment Program (CCAP) - 2015",
        "dc_title_fr_s":"Masque agricole de 1 km du Programme d'évaluation de l'état des cultures (CCAP) - 2015",
        "solr_geom":"ENVELOPE(-143.782063, -46.38161, 62.281322, 40.184321)",
        "dct_issued_s":"2018-10-01",
        "dc_publisher_s":"Open Data Canada",
        "layer_geom_type_s":"Undetermined",
        "dct_provenance_s":"Open Data Canada",
        "dc_identifier_s":"https://open.canada.ca/data/en/dataset/f48efc96-a51f-40f9-aaa0-90797f92e269",
        "dc_description_en_s":"The following dataset correspond to the 1 km agricultural mask from Statistics Canada’s Crop Condition Assessment Program (CCAP). The mask have been generated from the classes 110 to 199 of the 2015 Agriculture and Agri-Food Canada’s landcover classification. The selection was then generalized to a spatial resolution of 1 km. The 2015 mask was used from the 2015 to the 2018 growing seasons inclusively. ",
        "dc_description_fr_s":"L'ensemble de données suivant correspond au masque agricole de 1 km du Programme d'évaluation de l'état des cultures (PEEC) de Statistique Canada. Les masques ont été générés à partir des classes 110 à 199 de la classification de la couverture du sol 2015 d'Agriculture et Agroalimentaire Canada. La sélection a ensuite été généralisée à une résolution spatiale de 1 km. Le masque 2 015 a été utilisé des saisons de croissance 2015 à 2018 inclusivement. ",
        "dct_references_s":"{\"http://lccn.loc.gov/sh85035852\":\"https://geo.frdr-dfdr.ca/metadata/geodisy/open/f48efc96-a51f-40f9-aaa0-90797f92e269/iso19139.zip\",\"http://schema.org/url\":\"https://open.canada.ca/data/en/dataset/f48efc96-a51f-40f9-aaa0-90797f92e269\"}",
        "dc_creator_sm":["INFOSTATS"],
        "dct_affiliation_sm":["Rossi, Giulia S.: University of Guelph", "Cramp, Rebecca L.: University of Guelph", "Wright, Patricia A.: University of Guelph", "Franklin, Craig E.: University of Guelph"],
        "dct_contributor_sm":["Barnett, James; Verela, Brandon; Jennings, Ben; Lesbarreres, David; Pruitt, Jonathan; Green, David"],
        "dc_series_sm": ["University of Guelph Research Data Repository // College of Biological Science"],
        "dct_publisher_sm": ["University of Guelph Libraries"],
        "geoblacklight_version":"1.0",
        "layer_id_s":"open_f48efc96-a51f-40f9-aaa0-90797f92e269",
        "timestamp":"2021-10-07T21:35:43.908Z"}

### CODE REVIEW

**Comment by pdante-ubc** [comment]
Your metadata listed for this pull request does not include "dc_title_s" as a field, so the title being displayed in the search results is ending up as a the slug for some reason (and a search for the actual title returns nothing, while still giving the autocomplete option of the full title).

**Review by pdante-ubc — COMMENTED** [review]
The figma example seems to indicate that all the hyperlinks are supposed to be underlined, even when not hovered over, to provide non-color indicator that they are links.

**Comment by pdante-ubc** [comment]
The button that currently says "View Citation" should say "Copy Citation", but for the life of me I'm not finding where that button is being labeled. I cannot find the words "View Citation" anywhere in our GBL code, the source GBL code, or in the source BL code, so I have no idea where you should change that.

**Comment by pdante-ubc** [comment]
The expansion of descriptions that run too long currently says "read more" but sigma requests "Show full description". You probably already know how to do this, but if you don't or just don't remember at the moment (https://codepen.io/joserick/pen/ooVPwR) shows an easy example.

**Comment by pdante-ubc** [comment]
I'm assuming you did not update the Harvester to change Access to "Open" rather than "Public"? I'll add a JIRA issue for myself to do that unless I hear otherwise from you.

**Comment by adammckenzie** [comment]
Hi @pdante-ubc 

For this comment
> Your metadata listed for this pull request does not include "dc_title_s" as a field, so the title being displayed in the search results is ending up as a the slug for some reason (and a search for the actual title returns nothing, while still giving the autocomplete option of the full title).

That is outside the scope of this pull request. I have filed https://computecanada.atlassian.net/browse/RDM-5676 so that we don't forget to fix this.

**Comment by adammckenzie** [comment]
> The figma example seems to indicate that all the hyperlinks are supposed to be underlined, even when not hovered over, to provide non-color indicator that they are links.

Good catch. I've made them all underlined.

**Comment by adammckenzie** [comment]
>

**Comment by adammckenzie** [comment]
> The button that currently says "View Citation" should say "Copy Citation", but for the life of me I'm not finding where that button is being labeled. I cannot find the words "View Citation" anywhere in our GBL code, the source GBL code, or in the source BL code, so I have no idea where you should change that.

We discussed this in a redesign meeting that Copy Citation implies that it will copy it as soon as you click on it so I think we settled on View Citation as an alternative.

**Comment by adammckenzie** [comment]
> The expansion of descriptions that run too long currently says "read more" but sigma requests "Show full description". You probably already know how to do this, but if you don't or just don't remember at the moment (https://codepen.io/joserick/pen/ooVPwR) shows an easy example.

Good catch I have fixed this.

**Pull request merged**
